dist: xenial
language: node_js

node_js:
- '8'

env:
- WORKING_DIR=buyer-app/buyer-app SKIP_AUDIT=true SKIP_TESTS=true
- WORKING_DIR=buyer-api SKIP_AUDIT=false SKIP_TESTS=true
- WORKING_DIR=buyer-signing-service SKIP_AUDIT=false SKIP_TESTS=true

cache:
  directories:
  - "$WORKING_DIR/node_modules"

before_install: npm i -g npm@6.1.0 codecov@3.1.0

install:
- cd $WORKING_DIR
- npm install

before_script:
  - npm run lint
  # TODO: Make these steps compulsive
  - npm audit || $SKIP_AUDIT
  - npm run test:coverage:ci || $SKIP_TESTS
  - codecov || $SKIP_TESTS

script: npm run build

before_deploy: npm run publish

deploy:
  provider: releases
  api_key:
    secure: qYSbn3B8FM673cADwbe7T5dDAwsQ9H5lLAiGnIbp3ZYxpAcFo6yprNb1LvwtPArp/7HwDpycdDx0a2hC3fBSkhUkbKcHIzyGpTaFIum5Ffm8Cwnuu4uOwrx4G5/CZrpZlha75lHuRCvvjUHIEBVwXsuizpbn4qXoAn+aJyzwKlVZBabPyjBFyv0qxqsYKDgQ4mFnEgrL+vY2A3C9WdIZ9fsyAf9jJeFqcpV1eHb8wTL887p4Gm9oWVjNalaagXn/66NAOJcvC3W2e2ZGyEyWzxVqLUHBAenF8SyMOEe+VBMCY9ewfCaGrnrlZGnWungE3I966eYoEBPcUBJsTWesonJznY5WTyVpaSVRpOSk1BjWi3JjeKrosWTGprRKX9JfdeecFrrr2hLTzwAZxJ5X6zdDGPo8oFtg/qyhHK9ava5Jr2FhjfHy1QkYLr5k6/T7I1uDKZjUl8Ng8KtU9uKDPpRH69TbUYsbq2VNCOC/yAMxOfIWa/vj+Pn6kzl0G2f2ucWwRgadVyTHtsXhRDV6No1lCG5kUyfN9cxc2DnPcY2erYo4dqMiFHDcoBpYN03f3kuyG65xkyTpzsq+37nPFMt6jFjh206VWXCt7qHs4pgyVbhdRXV8k1W6QikFTuODpCH6ddEs0ptVa5YKBvOj0bHYAHGWfFiVOgE7E9UnOHk=
  file_glob: true
  file: "artifacts/*.tar.gz"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
  slack:
    rooms:
      - secure: $SLACK_SECURE_KEY
    on_success: change
    on_failure: change
