language: node_js

node_js:
- '8'

env:
- WORKING_DIR=buyer-app/buyer-app
- WORKING_DIR=buyer-api
- WORKING_DIR=buyer-signing-service

cache:
  directories:
  - "$WORKING_DIR/node_modules"

before_install: npm i -g npm@6.1.0 codecov@3.1.0

install:
- cd $WORKING_DIR
- npm install

before_script:
  - npm run lint
  - npm audit
  - npm run test:coverage:ci
  - codecov

script: npm run build

before_deploy: npm run publish

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_RELEASES_SECURE_KEY
  file: "artifacts/*.tar.gz"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
  slack:
    rooms:
      secure: $SLACK_SECURE_KEY
      on_success: change
      on_failure: change
