language: node_js

node_js:
- '8'

env:
- WORKING_DIR=buyer-app/buyer-app SKIP_AUDIT=true SKIP_TESTS=true
- WORKING_DIR=buyer-api SKIP_AUDIT=false SKIP_TESTS=true
- WORKING_DIR=buyer-signing-service SKIP_AUDIT=false SKIP_TESTS=true

cache:
  directories:
  - "$WORKING_DIR/node_modules"

before_install: npm i -g npm@6.1.0 codecov@3.1.0

install:
- cd $WORKING_DIR
- npm install

allow_failures:
  - env: ALLOW_FAILURE=true

before_script:
  - npm run lint
  # TODO: make these steps compulsive
  - npm audit || $SKIP_AUDIT
  - npm run test:coverage:ci || $SKIP_TESTS
  - codecov || $SKIP_TESTS

script: npm run build

before_deploy: npm run publish

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_RELEASES_SECURE_KEY
  file: "artifacts/*.tar.gz"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
  slack:
    rooms:
      secure: $SLACK_SECURE_KEY
      on_success: change
      on_failure: change
