dist: xenial
language: node_js
if: type = pull_request OR tag IS present
node_js:
  - "8"

env:
  - WORKING_DIR=buyer-app/buyer-app SKIP_AUDIT=true SKIP_TESTS=true
  - WORKING_DIR=buyer-api SKIP_AUDIT=true SKIP_TESTS=false
  - WORKING_DIR=buyer-signing-service SKIP_AUDIT=true SKIP_TESTS=false

cache:
  directories:
    - "$WORKING_DIR/node_modules"

before_install: npm i -g npm@6.1.0

install:
  - cd $WORKING_DIR
  - npm install

before_script:
  - npm run lint
  # TODO: Make these steps compulsive for buyer app
  - $SKIP_AUDIT || npm audit
  - $SKIP_TESTS || npm run test:coverage
  - $SKIP_TESTS || bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info

script: npm run build

before_deploy: npm run publish

deploy:
  provider: releases
  api_key:
    secure: qYSbn3B8FM673cADwbe7T5dDAwsQ9H5lLAiGnIbp3ZYxpAcFo6yprNb1LvwtPArp/7HwDpycdDx0a2hC3fBSkhUkbKcHIzyGpTaFIum5Ffm8Cwnuu4uOwrx4G5/CZrpZlha75lHuRCvvjUHIEBVwXsuizpbn4qXoAn+aJyzwKlVZBabPyjBFyv0qxqsYKDgQ4mFnEgrL+vY2A3C9WdIZ9fsyAf9jJeFqcpV1eHb8wTL887p4Gm9oWVjNalaagXn/66NAOJcvC3W2e2ZGyEyWzxVqLUHBAenF8SyMOEe+VBMCY9ewfCaGrnrlZGnWungE3I966eYoEBPcUBJsTWesonJznY5WTyVpaSVRpOSk1BjWi3JjeKrosWTGprRKX9JfdeecFrrr2hLTzwAZxJ5X6zdDGPo8oFtg/qyhHK9ava5Jr2FhjfHy1QkYLr5k6/T7I1uDKZjUl8Ng8KtU9uKDPpRH69TbUYsbq2VNCOC/yAMxOfIWa/vj+Pn6kzl0G2f2ucWwRgadVyTHtsXhRDV6No1lCG5kUyfN9cxc2DnPcY2erYo4dqMiFHDcoBpYN03f3kuyG65xkyTpzsq+37nPFMt6jFjh206VWXCt7qHs4pgyVbhdRXV8k1W6QikFTuODpCH6ddEs0ptVa5YKBvOj0bHYAHGWfFiVOgE7E9UnOHk=
  file_glob: true
  file: "artifacts/*.tar.gz"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
  slack:
    rooms:
      - secure: O33MiwjpOnGSeEGQaRwkdCL93IWQG5Izw+GWGkKZKZuA+OvRfeeYb6ECykLXzL9a0w+NDHwwzejgVrgFPxxTebB76VK/QIRze5x1obmd5DMIBtzGvS2+rJRbmmYIZAey0r80/+ZrhM3yZnZMJ1INIQVW5sLC4vi97J0Goy63A4JONLADldPhC61EPAB6HfjmrGXShA5ytLnVdjzEiBDl7vkvIgMwS7q3RMbCt4LO8nhOtDpTD46D0c0x6xB6NIE0oEUqtsSVXVHQteSQZqUBqnQmN4Af572pS8M2kGVtlfiZIKqE1BZqmBaMpw7WWKse4N0m5nCjxV3AP/Ff7UVuMKI7rgFjuMeRGrdKLG7e4POtRzGH5jLckKDvg1p09XVUv2XHEPKyL+a/lxU5eSTcAbXZgBgrlfxyC/XDRkc5R1770cyK8HsNDppwaMkE363mVdl4gLBMcsSg0IASnWGlVTiR8HAc9iAkT7xHLq/a+toC1xr/rtUQgQ/5nmAu+DQ24hC8hStKLbIvjvl7Bd5nsMyRHBUwzPkbm0dryNDDUD9OR3Xv4gBO6C9LCV5Jvjw7itBeGAU/SWxmvCXAjJo/XUnbhybt7cA3Ko8QQXFYZmhGi/MQBif+FE/R9sgTrGlnrurrPJQgusY9V20IwuPildnWV/gIhhvwiR32E0t3xZg=
    on_success: change
    on_failure: change
